spring:
    application:
        name: microservice-customer

microservice-customer:
    url: https://customer.microservicesdemo.net/customer/api/v1/

data:
    mongodb:
        uri: mongodb+srv://mkmongouser:Secret_Password@cluster0.yu4x6.mongodb.net
        database: customer

server:
    port: 8080
    servlet:
        context-path: /customer
